### ISSUE TITLE
test-011.mysh fails with Bash due to output from cd -

### ISSUE THREAD

**Issue by guillaumejchauveau** [devnull-cz/unix-linux-prog-in-c-labs#3]
I noticed that the test 11 fails with Bash as the "cd -" command outputs the previous directory:
```
010     PASS
011     FAIL
== 8< BEGIN diff output ==
--- test-output-011.txt 2019-11-13 20:53:37.539641300 +0100
+++ stef-output-file.data       2019-11-13 21:30:54.591015900 +0100
@@ -1,3 +1,4 @@
 /tmp
 /etc
 /tmp
+/tmp
== 8< END diff output=====
012     PASS
```
I thought this was worth creating an issue since the test script recommands checking with Bash first.

**Comment by janpgit** [comment]
Thanks for letting us know, I just fixed that.  I will also update the shell assignment.
